### ISSUE TITLE
Is there any official supported docker image?

### ISSUE THREAD

**Issue by ajohnstone** [Appdynamics/docker-machine-agent#1]
Is there any official supported docker image? @mqprichard 
Currently its expected to build your own docker images with the machine agent after downloading the source. As per https://github.com/Appdynamics/docker-machine-agent/blob/master/Dockerfile#L15-L18

What about?
https://github.com/Appdynamics/extensions-docker/blob/master/docker-machineagent/docker-compose.yml

https://github.com/markjeffery/appd_machine_agent_kubernetes/issues/1

**Comment by mqprichard** [comment]
@ajohnstone That's correct - today, we ask you to download the machine agent (for license reasons) and build the docker image locally.  I would like to be able to ship an official supported docker image but not able to do so right now. 

Those other projects are for machine agent extensions: this example is designed to work with the built-in Docker support that we introduced in 4.3.3.  I'll update the READMEs for those projects to make that clear.

**Comment by bencoughlan** [comment]
Any sign of a supported image coming in the near future, NewRelic provide one and it's infinitely better than this current solution.
