### ISSUE TITLE
start-appdynamics: not found

### ISSUE THREAD

**Issue by venkatmarella** [Appdynamics/docker-machine-agent#2]
Hi,

I used docker file and run the container with created image. What could be the issue, I tried compose file also landed in same issue.

[docker@xxxxx appD_agent_compose]$ docker build -t appdynamics/docker-machine-agent:v1 .                                                                                           Sending build context to Docker daemon  167.7MB
Step 1/8 : FROM ubuntu:14.04
14.04: Pulling from library/ubuntu
bae382666908: Pull complete
29ede3c02ff2: Pull complete
da4e69f33106: Pull complete
8d43e5f5d27f: Pull complete
b0de1abb17d6: Pull complete
Digest: sha256:6e3e3f3c5c36a91ba17ea002f63e5607ed6a8c8e5fbbddb31ad3e15638b51ebc
Status: Downloaded newer image for ubuntu:14.04
 ---> dea1945146b9
Step 2/8 : RUN apt-get update &&     apt-get upgrade -y &&     apt-get install -y unzip &&     apt-get clean
 ---> Running in 63fa5d47cc11
Ign http://archive.ubuntu.com trusty InRelease
Get:1 http://security.ubuntu.com trusty-security InRelease [65.9 kB]
Get:2 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
Get:3 http://security.ubuntu.com trusty-security/universe Sources [76.4 kB]
Get:4 http://archive.ubuntu.com trusty-backports InRelease [65.9 kB]
Get:5 http://archive.ubuntu.com trusty Release.gpg [933 B]
Get:6 http://security.ubuntu.com trusty-security/main amd64 Packages [831 kB]
Get:7 http://archive.ubuntu.com trusty-updates/universe Sources [241 kB]
Get:8 http://security.ubuntu.com trusty-security/restricted amd64 Packages [17.8 kB]
Get:9 http://archive.ubuntu.com trusty-updates/main amd64 Packages [1277 kB]
Get:10 http://security.ubuntu.com trusty-security/universe amd64 Packages [238 kB]
Get:11 http://security.ubuntu.com trusty-security/multiverse amd64 Packages [3997 B]
Get:12 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [21.1 kB]
Get:13 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [552 kB]
Get:14 http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages [15.5 kB]
Get:15 http://archive.ubuntu.com trusty-backports/main amd64 Packages [14.8 kB]
Get:16 http://archive.ubuntu.com trusty-backports/restricted amd64 Packages [40 B]
Get:17 http://archive.ubuntu.com trusty-backports/universe amd64 Packages [52.6 kB]
Get:18 http://archive.ubuntu.com trusty-backports/multiverse amd64 Packages [1396 B]
Get:19 http://archive.ubuntu.com trusty Release [58.5 kB]
Get:20 http://archive.ubuntu.com trusty/universe Sources [7926 kB]
Get:21 http://archive.ubuntu.com trusty/main amd64 Packages [1743 kB]
Get:22 http://archive.ubuntu.com trusty/restricted amd64 Packages [16.0 kB]
Get:23 http://archive.ubuntu.com trusty/universe amd64 Packages [7589 kB]
Get:24 http://archive.ubuntu.com trusty/multiverse amd64 Packages [169 kB]
Fetched 21.0 MB in 39s (537 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  zip
The following NEW packages will be installed:
  unzip
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 157 kB of archives.
After this operation, 395 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty-updates/main unzip amd64 6.0-9ubuntu1.5 [157 kB]
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Fetched 157 kB in 0s (1066 kB/s)
Selecting previously unselected package unzip.
(Reading database ... 11569 files and directories currently installed.)
Preparing to unpack .../unzip_6.0-9ubuntu1.5_amd64.deb ...
Unpacking unzip (6.0-9ubuntu1.5) ...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Setting up unzip (6.0-9ubuntu1.5) ...
 ---> 5747d109634d
Removing intermediate container 63fa5d47cc11
Step 3/8 : ENV MACHINE_AGENT_HOME /opt/appdynamics/machine-agent
 ---> Running in 8591152e8fd5
 ---> f42f0dff64e9
Removing intermediate container 8591152e8fd5
Step 4/8 : ADD machine-agent.zip /tmp/
 ---> 7360794ed843
Removing intermediate container f24a229e9fce
Step 5/8 : RUN mkdir -p ${MACHINE_AGENT_HOME} &&     unzip -oq /tmp/machine-agent.zip -d ${MACHINE_AGENT_HOME} &&     rm /tmp/machine-agent.zip
 ---> Running in cc15f8c5d825
 ---> b73f92ffc120
Removing intermediate container cc15f8c5d825
Step 6/8 : ADD start-appdynamics ${MACHINE_AGENT_HOME}
 ---> 6a9e45d3bafe
Removing intermediate container 1ec44f823f2c
Step 7/8 : RUN chmod 744 ${MACHINE_AGENT_HOME}/start-appdynamics
 ---> Running in 2b434e6bf218
 ---> 0b3f1773ef00
Removing intermediate container 2b434e6bf218
Step 8/8 : CMD "${MACHINE_AGENT_HOME}/start-appdynamics"
 ---> Running in 5b2b1c0fc297
 ---> 25d2d6d06a1a
Removing intermediate container 5b2b1c0fc297
Successfully built 25d2d6d06a1a
Successfully tagged appdynamics/docker-machine-agent:v1
[docker@xxxxx appD_agent_compose]$ docker run --rm -it   -e APPD_HOST=xxxx.saas.appdynamics.com   -e APPD_PORT=443   -e APPD_SSL_ENABLED=true   -e APPD_ACCOUNT_NAME=xxxxx -e APPD_ACCESS_KEY=xxxxxx -v /:/hostroot:ro -v /var/run/docker.sock:/var/run/docker.sock appdynamics/docker-machine-agent:v1
/bin/sh: 1: /opt/appdynamics/machine-agent/start-appdynamics: not found

**Comment by venkatmarella** [comment]
@mqprichard 

Do you have any idea on this?

**Comment by cbrahms** [comment]
The error /bin/sh: 1: not found can be caused by the file encoding not being UTF-8.  Switching to UTF-8 (or running 'dos2unix start-appdynamics') resolved this issue.

**Comment by venkatmarella** [comment]
Thanks @cbrahms . It worked!
